local u = require("ppm.utils")
local k = require("ppm.keymaps")

u.nquickmap(k.search.file_cwd, [[<cmd>Telescope find_files cwd=%:p:h<cr>]])
u.nquickmap(k.search.grep, [[<cmd>Telescope live_grep_args<cr>]])
u.nquickmap(k.search.buffer, [[<cmd>Telescope buffers<cr>]])
u.nquickmap(k.search.oldfile, [[<cmd>Telescope oldfiles<cr>]])
u.nquickmap(k.search.file, [[<cmd>Telescope find_files<cr>]])
u.nquickmap(k.search.git_file, [[<cmd>Telescope git_files<cr>]])
u.nquickmap(k.search.grep_cursor, [[<cmd>Telescope grep_string<cr>]])
u.nquickmap(k.search.help_tags, [[<cmd>Telescope help_tags<cr>]])
u.nmap("<leader>e", [[<cmd>Telescope file_browser<cr>]], "Browe files")
u.nmap("<leader>r", [[<cmd>Telescope resume<cr>]], "Resume Telescope")
