tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
# Lightweight and flexible command-line JSON processor
# Collaborative design tool with support for Sketch files
cask "abstract"
# Application launcher and productivity software
cask "alfred"
# Web browser focusing on privacy
cask "brave-browser"
# Trains AIs to understand and translate texts
cask "deepl"
# Visually compare and merge files
cask "diffmerge"
# Web browser
cask "firefox", args: { language: "en" }
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-hasklug-nerd-font"
cask "font-inconsolata"
# Typeface made for developers
cask "font-jetbrains-mono"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Free and open-source image editor
cask "gimp"
# Tool to optimize images to a smaller size
cask "imageoptim"
# Password manager app
cask "keepassxc"
# GPU-based terminal emulator
cask "kitty"
# Open-source Markdown editor
cask "macdown"
# Web browser
cask "microsoft-edge"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Team communication and collaboration software
cask "slack"
# Graphical client for Git version control
cask "sourcetree"
# Real time file synchronization software
cask "syncthing"
# Open-source code editor
cask "visual-studio-code"
vscode "bierner.color-info"
vscode "Catppuccin.catppuccin-vsc"
vscode "guillaumedoutriaux.name-that-color"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.vscode-typescript-next"
vscode "royaction.color-manager"
vscode "styled-components.vscode-styled-components"
vscode "sumneko.lua"
# Text processor and publishing toolchain for AsciiDoc
brew "asciidoctor"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Diff that understands syntax
brew "difftastic"
# Maintain consistent coding style between multiple editors
brew "editorconfig"
# LLVM bytecode to JavaScript compiler
brew "emscripten"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Fast partial replacement for the codemod tool
brew "fastmod"
# Simple, fast and user-friendly alternative to find
brew "fd"
# macOS CLI for managing custom icons for files and folders
brew "fileicon"
# Terminal JSON viewer
brew "fx"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Image processing tools collection
brew "graphicsmagick"
# GNU grep, egrep and fgrep
brew "grep"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
brew "jq"
# Pager program similar to more
brew "less"
# SIXEL encoder/decoder implementation
brew "libsixel"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Show markdown documents on text terminals
brew "mdcat"
# Unified display of technical and tag data for audio/video
brew "media-info"
# Nice to use pager for humans
brew "moar"
# Node version management
brew "n"
# HTTP/2 C Library
brew "nghttp2"
# Small build system for use with gyp or CMake
brew "ninja"
# Paragraph reflow for email
brew "par"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# File browser
brew "ranger"
# SVG rendering tool and library
brew "resvg"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Nodejs-based tool for optimizing SVG vector graphics files
brew "svgo"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Granddaddy of HTML tools, with support for modern standards
brew "tidy-html5"
# Program that allows you to count code, quickly
brew "tokei"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# URL extractor/launcher
brew "urlview"
# Image processing library
brew "vips"
# Simple terminal image viewer written in Rust
brew "viu"
# Pager/text based browser
brew "w3m"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"