"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status \
$cmd_duration\
$fill\
$git_metrics\
$git_commit\
$line_break\
$package\
${custom.git_email}\
$jobs\
$character"""

right_format = """
$python"""
# ${custom.command_number}"""

[directory]
read_only = "  "
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[fill]
symbol = ' '

[git_branch]
format = "[$symbol$branch(:[$remote_name/$remote_branch](red))]($style)"
style = "bright-black"
always_show_remote = false
symbol = " "

[git_commit]
format = '[( $hash)$tag]($style)'
only_detached = false
tag_disabled = false
tag_symbol = "  "

[git_status]
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
stashed= " "
ahead= "⇡"
behind= "⇣"
up_to_date= " "
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
conflicted= "C"
deleted= "D"
renamed= "R"
modified= "M"
staged= "S"
untracked= "U"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[jobs]
format = ' [$symbol$number]($style)'
symbol = " "

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nodejs]
format = '[$symbol($version )]($style)'
detect_extensions = ['js', 'jsx', 'mjs', 'cjs', 'ts', 'tsx', 'mts', 'cts']

[package]
format = '[$symbol$version]($style)'
symbol = ' '

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[custom.command_number]
command = "echo %h"
when = "true"
format = "[$output](yellow)"

[custom.git_email]
format = " [$output]($style)"
style = "bright-black"
shell = ["git", "config", "--get"]
command = 'user.email'
use_stdin = false
detect_folders = ['.git']
detect_files = ['.git']