# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  border: 'rounded'
  nerdFontsVersion: '3'
  shortTimeFormat: '15h04'
  timeFormat: '02/01/2006'
os:
  editPreset: 'nvim'