# Show prettier tables in reports
--pretty

# Postpone balance assertions until you use -s or `hledger check assertions`.
# It means less need to add -I while piping or fixing problems.
# --ignore-assertions