" .gvimrc

color twilight_pioupioum

if has("autocmd")
  autocmd! bufwritepost .gvimrc source $MYGVIMRC
endif
" Masquer le superflu de MacVim
set guioptions=aAce

" Surligner la ligne courante
set cursorline

set guifont=Menlo:h11

