" .gvimrc
" Author: Mehdi Kabab <http://pioupioum.fr>
" Source: http://github.com/piouPiouM/dotfiles/vim/gvimrc
" 
" 1. Basic configuration
" 2. Mappings

" Section: Basic configuration {{{1
" ----------------------------

color solarized
set background=light
silent! set transparency=1 " Make my coding sessions more fun

if has("autocmd")
  autocmd! bufwritepost .gvimrc source $MYGVIMRC
endif
" Masquer le superflu de MacVim
set guioptions=aAce

" }}}1
" Section: Mappings {{{1
" -----------------

" Syntax highlighting hex values {{{2
" http://vimcasts.org/e/25
if exists('*HexHighlight()')
  nmap <leader>h :call HexHighlight()<Return>
endif

" }}}2
" }}}1

if filereadable(expand("~/.local.gvimrc"))
  source ~/.local.gvimrc
endif

