
if [ -f "$HOME/.profile" ]; then
    source $HOME/.profile
fi

if [ -f "$HOME/.bashrc" ]; then
    source $HOME/.bashrc
fi

if [ -s "$HOME/.rvm/scripts/rvm" ]; then
    source "$HOME/.rvm/scripts/rvm"
fi
