BREW_PREFIX=`brew --prefix`

if [ -f "$HOME/.profile" ]; then
    source $HOME/.profile
fi

if [ -f "$HOME/.bashrc" ]; then
    source $HOME/.bashrc
fi

export USER_BASH_COMPLETION_DIR=~/.bash_completion.d
if [ -f $BREW_PREFIX/etc/bash_completion ]; then
    . $BREW_PREFIX/etc/bash_completion
fi

